### ISSUE TITLE
The deb files on http://checkmate.gissen.nl/download.php are very old. Could you please update them?

### ISSUE THREAD

**Issue by jaimet** [Sjord/checkmate#31]
Hi.

The mpck .deb files on http://checkmate.gissen.nl/download.php are very old (version 0.12 from approx 2006). Could you please update them?

BTW, thank you for writing checkmate/mpck - I've been using it on debian for years, and I'm very grateful to you.

With kind regards, Jaime

**Comment by Sjord** [comment]
Thank you for submitting an issue, Jaime. I have build a new debian package. Could you test out this [mpck_0.21-1_amd64.deb](https://github.com/Sjord/checkmate/releases/download/v0.21/mpck_0.21-1_amd64.deb)?

**Comment by jaimet** [comment]
Hi Sjoerd. The .deb file installs correctly, the binary works perfectly, and all the other files (man page and documentation) are all in the correct places.

I don't know whether you intend to update mpck_0.12-1_i386.deb but if you do, I still have an i386 (32-bit) architecture machine that I can use to test it too, and I will be happy to do so if you want.

Thanks again for doing all of this! Jaime

**Comment by Sjord** [comment]
I have also updated http://checkmate.gissen.nl/download.php, so this seems done.
