### ISSUE TITLE
GUI: attempting to scan folder doesn't quite work

### ISSUE THREAD

**Issue by Ryder17z** [Sjord/checkmate#37]
It scans, then doesn't give any output, instead, it goes back to the state before attempting to scan the folder

**Comment by Sjord** [comment]
It's supposed to indicate the result of the scan by changing the little icons in front of files and directories.

**Comment by Ryder17z** [comment]
I didn't watch the software after selecting scan as I thought it may take a while, then didn't notice the changes when looking at it again. I was expecting a popup window with a report of sorts as i'm very used to that behavior.

My mistake.
